### ISSUE TITLE
Untrusted and broken URLs

### ISSUE THREAD

**Issue by objectiveSee** [PGPHarvard/pgp_survey_analysis#1]
The links in the README are producing warnings about untrusted connection. If you proceed, you will get an error saying that the page you are looking for is missing.  For example: https://my.personalgenomes.org/google_surveys/9

**Comment by tfmorris** [comment]
This is being caused by server misconfiguration at Harvard. The SSL cert being used is actually for "*.pgp-hms.org" instead of "my.personalgenomes.org". The issue needs to be fixed there by a server admin.

**Comment by madprime** [comment]
Actually, it's the URLs that should be updated, not the server / cert. Sorry I missed this @objectiveSee. @tfmorris's comment is reminding me to fix it.

**Comment by tfmorris** [comment]
Thanks for the fix, but you might want to let the server admin know too. In my opinion, the server shouldn't reply to https://my.personalgenomes.org/ if it doesn't have a certificate for it.
